### PR TITLE
LPS-108859 Provide traffic sources to UI

### PR DESCRIPTION
**Pull request by darquesdev**
Hi @cgoncas, I've followed your suggestions in order to make it simpler and consistent with types. Thanks for the review :)

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:relevant

**Pull request closed without merging**
