### PR TITLE
LPS-108859 Provide traffic sources to UI

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/123. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/b63e1c0eb7db~2...b63e1c0eb7db) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
