### PR TITLE
LPS-98559 Update DXP and AC experiments after updating related entities (A/B Testing)

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/874. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/576970662591~4...576970662591) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
