### PR TITLE
LPS-101063 As a site admin it should be possible to configure segmentation condition values based on taxonomy of predefined values

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by darquesdev** [comment]
As we agreed in the previous conversation I'm closing this PR

**Pull request closed without merging**
