### PR TITLE
LPS-112357 Support View acton in Content Dashboard

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Continues in https://github.com/darquesdev/liferay-portal/pull/163

**Comment by darquesdev** [comment]
https://github.com/darquesdev/liferay-portal/pull/163

**Pull request closed without merging**
