### PR TITLE
LPS-111278 We don't need this to be immediate

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/87174. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
