### PR TITLE
LPS-94855 Include key in request

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@dgarciasarai

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72415. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
