### PR TITLE
LPS-111589 | LPS-111595 Inject Analytics Cloud connection status

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/198. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/1434c3469204~1...1434c3469204) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
