### PR TITLE
LPS-110727 DXP - Include search keywords for organic & paid traffic sources

### PR DESCRIPTION
**Pull request by darquesdev**
@cgoncas @dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:open

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
@darquesdev , da un conflicto :O

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
