### PR TITLE
LPS-111691 Site Administrator role should not be assignable to a SegmentsEntry

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111691](https://issues.liferay.com/browse/LPS-111691).<br><br>Hey @darquesdev, will you please review my changes to the Segments portlet? The goal with this change is to disallow selecting roles that do not allow assigning permission directly to them, similar to the ones excluded from the permissions selection dialog. Please let me know if you have any questions.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/1015. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
