### PR TITLE
LPS-114696 Not needed.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/156. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
