### PR TITLE
LPS-108859

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See comments in https://github.com/brianchandotcom/liferay-portal/pull/87023

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Hi @brianchandotcom I decided to chain the creation of the util classes as with `com.liferay.fragment.internal.validator.FragmentEntryValidatorImplTest#setUp`

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/121. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/0737d123766e~3...0737d123766e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
