### PR TITLE
LPS-107894 Call AC for Historical Views

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/458. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/b7e83f45c469~5...b7e83f45c469) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
