### PR TITLE
LPS-114987 Provide aggregated data by category and subtype/structure

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
Compile failure for content-dashboard
`    [exec] * What went wrong:`
`     [exec] Execution failed for task ':apps:content-dashboard:content-dashboard-web:compileJava'.`
`     [exec] > Compilation failed; see the compiler error output for details.`

[Full log can be found here](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/413204/consoleText)

**Pull request closed without merging**
