### PR TITLE
LPS-98833 Support condition field based on name and value of request parameter

### PR DESCRIPTION
**Pull request by dgarciasarai**
@darquesdev can you review this, please?

/cc @rotty3000 @epgarcia

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
This can be closed. See https://github.com/epgarcia/liferay-portal/pull/931

**Pull request closed without merging**
