### PR TITLE
LPS-110227 Category Navigation portlet is not shown for non-default experience

### PR DESCRIPTION
**Pull request by darquesdev**
From https://github.com/tinatian/liferay-portal/pull/1748

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
no longer need. See https://issues.liferay.com/browse/LPS-110227 to track the process

**Pull request closed without merging**
