### PR TITLE
LPS-108858 - DXP Rest client to connect to AC

### PR DESCRIPTION
**Pull request by darquesdev**
@cgoncas

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
🤞

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
🍀

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
/cc @jpince can you help us? Thanks.

**Comment by jpince** [comment]
CI got scared after you called for my help and obeyed :joy:

**Comment by dgarciasarai** [comment]
I'll take into account next time 😂

**Pull request closed without merging**
