### PR TITLE
LPS-107151 As a site admin, I want to assign site roles to site-level segments

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-107151](https://issues.liferay.com/browse/LPS-107151).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/1011. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/6109d906a896~7...6109d906a896) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
