### PR TITLE
LPS-98408 Update AC Experiment when DXP experiment is updated (A/B Testing)

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/869. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
