### PR TITLE
LPS-107151 segments-api - baseline

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Hi @drewbrokke , thanks for the contribution and for sending us the PR, it looks really good.

After reviewing the ticket acceptance criteria I have a question:
- What is the expected behavior when a site-role assigned to a segment is deleted?

On the other hand, as there's a test to check the permissions of a user here `com.liferay.segments.security.permission.contributor.test.SegmentsEntryRoleContributorTest#testHasPermission`, it would be very useful to have tests that verify the acceptance criteria described in the ticket:
1. When a site-level segment is assigned a site role, all users in that segment should be provisioned with the permissions defined for that site role
2. Conversely to (1), when a site-level role is unassigned from a segment, all segmented users should be de-provisioned.
3. Similarly to (2), when a segment is deleted, all segmented users should be de-provisioned.

Thank you very much in advance and let me know what you think about it.

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/1010. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@darquesdev thank you for looking this over. In my manual testing, the acceptance criteria were met, so I will provide test cases to cover those acceptance criteria. Would you like me to send a pull back to you once I do?

**Comment by darquesdev** [comment]
yes please! this will help us a lot to better understand this new feature and its code base. 

Please, don't forget this use case:
- What is the expected behavior when a site-role assigned to a segment is deleted?

Thanks again @drewbrokke !

**Pull request closed without merging**
