### PR TITLE
LPS-101063 As a site admin it should be possible to configure segmentation condition values based on taxonomy of predefined values

### PR DESCRIPTION
**Pull request by darquesdev**
from: https://github.com/rotty3000/liferay-portal/pull/1450/

- https://issues.liferay.com/browse/LPS-101063
- https://issues.liferay.com/browse/LPS-107362

CC: @rotty3000

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:stable

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Closing PR since this has been implmented here https://issues.liferay.com/browse/LPS-107362

**Pull request closed without merging**
