### PR TITLE
LPS-112721 Add tests.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
nicely done

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/144. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/c0a786be73d4~1...c0a786be73d4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
