### PR TITLE
LPS-115980 Provide boolean property for RTL

### PR DESCRIPTION
**Pull request by darquesdev**
@cgoncas @dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
https://github.com/darquesdev/liferay-portal/pull/184

**Comment by darquesdev** [comment]
continues here https://github.com/darquesdev/liferay-portal/pull/184

**Pull request closed without merging**
