### PR TITLE
LPS-108859 Provide traffic sources to UI

### PR DESCRIPTION
**Pull request by darquesdev**
@cgoncas @dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:test:tango-acceptance

**Comment by dgarciasarai** [comment]
Ups, that was for another PR 😅

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
