### PR TITLE
AB Tests UI

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/andresfulla/liferay-portal/pull/99. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/271. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/6cbf245bc668~7...6cbf245bc668) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
No te voy a engañar. No me la voy a leer.

**Comment by darquesdev** [comment]
jajaja, qué falso!

**Pull request closed without merging**
