### PR TITLE
[TECHNICAL-SUPPORT] LPS-109102 User Segment specific Assets Lists are not correctly published to live site

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @darquesdev ,

This change updates AssetListEntryAssetEntryRel.segmentsEntryId field correctly during staging.

Please review the changes.

cc: @laszlopap

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Thanks @vendeltoreki I'll review it later today

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Pull request submitted to https://github.com/vendeltoreki/liferay-portal/pull/39. [See changes here.](https://github.com/darquesdev/liferay-portal/compare/9082f55b6f3a~2...9082f55b6f3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
