### PR TITLE
LPS-108859 Provide traffic sources to UI

### PR DESCRIPTION
**Pull request by darquesdev**
@cgoncas @dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:stable

**Comment by darquesdev** [comment]
ci:test:stable

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Closing PR. New PR https://github.com/darquesdev/liferay-portal/pull/122

**Pull request closed without merging**
